### ISSUE TITLE
Stuck on customization

### ISSUE THREAD

**Issue by inzzanexo** [p3tr1ch0r/insomniaHUD#1]
Hey! I just got the hud, decided to open customization hud and now im stuck, i dont see the close button im on 1280x1024, the customization hud is stretched on this res plus upon restart it still opens in the customization.

**Comment by p3tr1ch0r** [comment]
Hey, unfortunately, 5:4 resolutions (Such as 1280x1024, the one you're using) are not supported, hence why the close button is cut off. You can forcefully exit the customization menu by going into your `tf/cfg/` folder and deleting `ih_custom.txt`.

**Comment by inzzanexo** [comment]
I see, understandable i changed res 👍
