### ISSUE TITLE
TimePanelValue is unaligned

### ISSUE THREAD

**Issue by Lite0** [p3tr1ch0r/insomniaHUD#13]
TimePanelValue is wider than ObjectiveStatusTimePanel causing it to shift towards the right in some servers
![unaligned timepanel](https://user-images.githubusercontent.com/40325859/220201521-eefb3905-08c5-4414-a3d2-e913c817e4bf.png)

hudmatchstatus.res
```
		"TimePanelValue"
		{
			"ControlName"							"CExLabel"
			"fieldName"								"TimePanelValue"
			"font"									"regular14"
			"fgcolor"								"Text0"
			"xpos"									"0"
			"ypos"									"0"
			"zpos"									"3"
			"wide"									"40"
			"tall"									"20"
			"visible"								"1"
			"enabled"								"1"
			"proportionaltoparent"					"1"
			"textAlignment"							"center"
			"labelText"								"0:00"
		}
```

**Comment by p3tr1ch0r** [comment]
Fixed alongside a few other bugs in 99631353728c4998467a83032d75bbdc8d699918
