### ISSUE TITLE
latest scream fortress update messed with the backpack and chat

### ISSUE THREAD

**Issue by Clyv1** [p3tr1ch0r/insomniaHUD#137]
![NVIDIA_Overlay_6NAbGQTJ69](https://github.com/user-attachments/assets/67148e43-cef5-4f4d-a7d1-80f2e53d9264)

**Comment by Clyv1** [comment]
![NVIDIA_Overlay_wt994WALoK](https://github.com/user-attachments/assets/9eba3236-715a-46e9-b6e3-f84fa3ace588)

**Comment by Clyv1** [comment]
oh and also matchmaking settings doesnt work, hasn't worked before the update

idrk how to fix this

**Comment by Clyv1** [comment]
![NVIDIA_Overlay_eaFgVvj0IL](https://github.com/user-attachments/assets/e02e3c35-a731-4536-98c2-0f5fc44c8a06)

**Comment by N1GHTM4R** [comment]
I am having same issue, :(

**Comment by Clyv1** [comment]
this messed up other huds too; its due to the new "UI SCALING" feature

**Comment by Clyv1** [comment]
and also customize doesn't work, pretty sure it hasn't been working even b4 the update

**Comment by Clyv1** [comment]
forget everything i said the hud creator is sketchy
