### ISSUE TITLE
help! i can't open Customization Menu on main menu

### ISSUE THREAD

**Issue by gaming11102006** [p3tr1ch0r/insomniaHUD#14]

**Comment by p3tr1ch0r** [comment]
Did you make sure to rename the folder?

**Comment by gaming11102006** [comment]
> Did you make sure to rename the folder?

That folder says "p3tr1ch0r-insomniaHUD-7b34e97"

**Comment by p3tr1ch0r** [comment]
Please read before making an issue then.
https://github.com/p3tr1ch0r/insomniaHUD/blob/master/README.md

**Comment by gaming11102006** [comment]
> Please read before making an issue then. https://github.com/p3tr1ch0r/insomniaHUD/blob/master/README.md

"very soon"? there is no guide?

**Comment by p3tr1ch0r** [comment]
Once again, please read.

**Comment by gaming11102006** [comment]
> Once again, please read. ![read](https://user-images.githubusercontent.com/87102884/220997221-0aff5e86-ad47-4ba5-94f7-8bdc9142e1e0.jpg) :/

oh ok but it doesn't work either

**Comment by p3tr1ch0r** [comment]
Well, make a new issue then. Next time, elaborate more and provide information and steps to reproduce the issue instead of just saying "ermmm it no worky :(("

**Comment by gaming11102006** [comment]
> Well, make a new issue then. Next time, elaborate more and provide information and steps to reproduce the issue instead of just saying "ermmm it no worky :(("

xd when a new update arrives, call me because I have no notifications
