### ISSUE TITLE
Customization not working properly

### ISSUE THREAD

**Issue by OutStanderREAL** [p3tr1ch0r/insomniaHUD#25]
Whenever I press the "Customize" button it just minimizes tf2 and brings it back up
The previous version 233 did the same thing, but the version before 233 did everything normally
![Screenshot_1](https://user-images.githubusercontent.com/127336751/223787981-8ba0958d-a83e-4e02-9762-0361ffdd4656.png)
Here is my custom folder, but I doubt anything here would be causing issuess

**Comment by p3tr1ch0r** [comment]
RTFM
