### ISSUE TITLE
tf2 freezes indefinetly with insomniaHUD when reshade is loading

### ISSUE THREAD

**Issue by itsilyuna** [p3tr1ch0r/insomniaHUD#35]
https://user-images.githubusercontent.com/132998455/237057484-0d815c98-c695-4907-b46c-9946d9b4e05f.mp4

installed (custom folder) mods:
mastercomfig
insomniaHUD itself

**Comment by p3tr1ch0r** [comment]
insomniahud forces a material reload at launch, so thats probably whats causing reshade to freak out. this is necessary in order for the dashboard dimmer to be properly sized. in`cfg/valve.rc`, commenting out line `39` should prevent this from happening, but things may look strange. i'd give it a shot.

**Comment by itsilyuna** [comment]
ill try it

**Comment by itsilyuna** [comment]
confirmed: does work, i don't see any visual glitches in the menu
