### ISSUE TITLE
ammo counter not showing (bug)

### ISSUE THREAD

**Issue by diemitze** [p3tr1ch0r/insomniaHUD#36]
![image](https://github.com/p3tr1ch0r/insomniaHUD/assets/80318198/f350081c-887b-4da1-a47d-89bada8f26db)

sometimes if i respawn it the ammo counter stops showing after i restart the game is shows again

**Comment by diemitze** [comment]
i dont get the bug again i guss it fix it self or so idk i get no console output

**Comment by HoppaC4** [comment]
https://www.teamfortress.tv/post/471087/ammo-disappearing
something to do with pressing inspect key ( 'f' by default ) and opening the scoreboard
im not sure if this is the problem in this case but im having this issue too sometimes
