### ISSUE TITLE
No Training Mode option 

### ISSUE THREAD

**Issue by lunaris-moon** [p3tr1ch0r/insomniaHUD#38]
Title is self explanatory, I know there's barely any people that would give a damn. No training mode option next to community servers, besides thee one that you can create servers but that ain't a training!!111
![image_2023-06-10_132708671](https://github.com/p3tr1ch0r/insomniaHUD/assets/125836443/d0ef38dc-b24b-4bbf-bb87-bd2633444a32)

**Comment by leadscales** [comment]
see #33

**Comment by lunaris-moon** [comment]
ah thanks
