### ISSUE TITLE
MVM Top menu issue

### ISSUE THREAD

**Issue by Doodybroy** [p3tr1ch0r/insomniaHUD#4]
![20230218121128_2](https://user-images.githubusercontent.com/121863405/219836930-820f9aa9-a12a-4b0f-af51-313f5884b6ab.jpg)

Only happens if minimal hud/ cl_hud_minmode 1 is enabled

**Comment by p3tr1ch0r** [comment]
minmode is currently not implemented, hence why the `valve.rc` disables it on launch. i'd suggest not enabling it until i've implemented it. please run `cl_hud_minmode 0`. it will be added soon, and that issue will be fixed.
