### ISSUE TITLE
I can't use customize settings

### ISSUE THREAD

**Issue by MichaelPL2XX1** [p3tr1ch0r/insomniaHUD#5]

**Comment by p3tr1ch0r** [comment]
some elaboration would be appreciated. what happens when you try and click the customize button? what gets echoed to the console on startup, and when you click it?

**Comment by haydenspb** [comment]
I have the same problem, when I press the customize button it unfocuses and refocuses my game and the console says this:
writing bindings to D:\SteamLibrary\steamapps\common\Team Fortress 2\tf\cfg\ih_custom.txt
#base ../custom/insomniaHUD/customization/_dev/customization_menu.res 
"mat_aaquality" = "1" ( def. "0" )
 archive
Changing resolutions from (1920, 1080) -> (1920, 1080)
Unable to remove d:\steamlibrary\steamapps\common\team fortress 2\tf\textwindow_temp.html!

**Comment by haydenspb** [comment]
It worked, thx

**Comment by p3tr1ch0r** [comment]
FYI this is in `README.md`. Please read before making an issue. Thank you. I'm gonna assume OP's issue was yours.
