### ISSUE TITLE
PlayerStatus overlapping

### ISSUE THREAD

**Issue by Lite0** [p3tr1ch0r/insomniaHUD#7]
with more than one status, the status icons will begin overlapping with hud elements. moving the icons down will fix this
![playerstatus overlaps health](https://user-images.githubusercontent.com/40325859/220186996-a3fbf630-484f-4561-ac71-260a5f64b98e.png)

hudplayerhealth.res
```
	"PlayerStatusAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"PlayerStatusAnchor"
		"xpos"										"10"
		"ypos"										"22"
		"wide"										"20"
		"tall"										"20"
		"visible"									"1"
		"enabled"									"1"

		"pin_to_sibling"							"PlayerStatusHealthValue"
		"pin_corner_to_sibling"						"PIN_CENTER_LEFT"
		"pin_to_sibling_corner"						"PIN_CENTER_RIGHT"
	}
```

**Comment by p3tr1ch0r** [comment]
Fixed in 7ec6d25c89757fe7d1509a7b4bb5c77621ca413b
