### ISSUE TITLE
Vaccinator resist icon overlapping

### ISSUE THREAD

**Issue by Lite0** [p3tr1ch0r/insomniaHUD#8]
looking at a teammate with the vaccinator out causes the resist icon to go over the player's name. moving the icon below the name fixes this
![overlapping vaccinator icon](https://user-images.githubusercontent.com/40325859/220187783-a47907ff-5585-4d86-a55c-27a01cee0579.png)

hudmediccharge.res
```
	"ResistIconAnchor"
	{
		"ControlName"								"EditablePanel"
		"fieldName"									"ResistIconAnchor"
		"xpos"										"cs-0.5"
		"ypos"										"c30"
		"wide"										"0"
		"tall"										"80"
		"visible"									"1"
		"enabled"									"1"
		"proportionaltoparent"						"1"
	}
```

**Comment by p3tr1ch0r** [comment]
Fixed in c45eb5b801eddedf66c395c59b1a247eb43bf41d
