### ISSUE TITLE
FreezePanel health gets cut off

### ISSUE THREAD

**Issue by Lite0** [p3tr1ch0r/insomniaHUD#9]
at certain health values the killer's health goes outside of the boundaries making it unreadable in most cases. widening the health panel fixes this
![freezepanel health gets cut off](https://user-images.githubusercontent.com/40325859/220188122-a19b7a60-6ea2-4599-bba8-03b98ef16128.png)

freezepanel_basic.res
```
		"FreezePanelHealth"
		{
			"ControlName"							"CTFFreezePanelHealth"
			"fieldName"								"FreezePanelHealth"
			"xpos"									"cs-0.5"
			"ypos"									"80"
			"zpos"									"1"
			"wide"									"40"
			"tall"									"f0"
			"visible"								"1"
			"enabled"								"1"
			"proportionaltoparent"					"1"
			"HealthBonusPosAdj"						"9"
			"HealthDeathWarning"					"0.49"
			"TFFont"								"bold18"
			"HealthDeathWarningColor"				"HealthHurt"
			"TextColor"								"HealthNormal"
		}
```

**Comment by p3tr1ch0r** [comment]
Fixed in bdde493ee2aa1cdab4080de5149e83328814d93e
